title: verdaccio
email: verdaccio.npm@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Lightweight private npm proxy registry
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://github.com/verdaccio/verdaccio"
twitter_username: verdaccio_npm
github_username:  verdaccio

# Build settings
markdown: kramdown
markdown_ext: md
exclude: [vendor]


author:
  name: verdaccio community
  url: https://verdaccio.github.io/

page_gen:
  - data: rules
    template: rule
    name: ruleName
    dir: rules
